# Spearman

In [16]:
from scipy.stats import spearmanr
from scipy.stats import rankdata

In [11]:
x = [1,2,3,4,5]
y = [5,6,7,8,7]
spearmanr(x, y)

SpearmanrResult(correlation=0.8207826816681233, pvalue=0.08858700531354381)

In [12]:
x = [106, 86, 100, 101, 99, 103, 97, 113, 112, 110]
y = [7, 0, 27, 50, 28, 29, 20, 12, 6, 17]

spearmanr(x, y)

SpearmanrResult(correlation=-0.17575757575757575, pvalue=0.6271883447764844)

In [27]:
x = [106, 86, 100, 101, 99, 103, 97, 113, 112, 110]
y = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 

spearmanr(x, y)

/Users/emiljoswin/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/emiljoswin/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/emiljoswin/anaconda3/envs/py37/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/Users/emiljoswin/anaconda3/envs/py37/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/Users/emiljoswin/anaconda3/envs/py37/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


SpearmanrResult(correlation=nan, pvalue=nan)

In [19]:
x = [1, 2, 3, 4]
y = [9, 8, 7, 5]

spearmanr(x, y)

SpearmanrResult(correlation=-1.0, pvalue=0.0)

In [21]:
rankdata(x)

array([1., 2., 3., 4.])

In [23]:
sorted(zip(x, y))

[(86, 0),
 (97, 0),
 (99, 0),
 (100, 0),
 (101, 0),
 (103, 0),
 (106, 0),
 (110, 0),
 (112, 0),
 (113, 0)]

In [24]:
rankdata(y)

array([5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5])

# Spearmans comparision between two submission files

In [41]:
from scipy.stats import spearmanr
from scipy.stats import rankdata
import pandas as pd

In [44]:
sub1 = pd.read_csv('submission-1.csv')
sub2 = pd.read_csv('submission-LSTM1.csv')
sub3 = pd.read_csv('submission-3.csv')

In [45]:
spearmanr(sub1['question_asker_intent_understanding'], sub2['question_asker_intent_understanding'] )

SpearmanrResult(correlation=-0.17779087007196126, pvalue=9.625114320641101e-05)

In [46]:
spearmanr(sub1['question_asker_intent_understanding'], sub3['question_asker_intent_understanding'] )

SpearmanrResult(correlation=0.6276081991883148, pvalue=1.694671306079919e-53)

In [39]:
sub1['question_asker_intent_understanding']

0      0.922307
1      0.840942
2      0.888614
3      0.810273
4      0.853046
         ...   
471    0.763972
472    0.814467
473    0.728414
474    0.882634
475    0.860409
Name: question_asker_intent_understanding, Length: 476, dtype: float64

In [40]:
sub2['question_asker_intent_understanding'] 

0      0.872352
1      0.866370
2      0.872587
3      0.866950
4      0.874695
         ...   
471    0.859003
472    0.873435
473    0.890932
474    0.876349
475    0.859503
Name: question_asker_intent_understanding, Length: 476, dtype: float64

In [42]:
rankdata(sub1['question_asker_intent_understanding'])

array([452., 257., 389., 133., 291., 403., 197., 434., 121., 228., 271.,
       114., 396., 247.,  42., 118.,  18., 323., 353., 397., 161., 220.,
       424., 211., 473., 215.,  15.,  46., 148., 164.,  56.,  88.,   7.,
       154., 419., 337.,   5., 425., 440., 182., 200.,  32., 156., 235.,
        80., 394.,  49., 413.,  89., 128., 259., 385.,  29., 263.,  61.,
       185., 392.,   3., 276.,  41., 332., 316., 429.,  47., 192., 387.,
       338.,  78., 427.,  53., 289.,  52., 294.,  64., 326., 430., 232.,
       375., 275., 155., 239., 225., 297., 209., 201., 258., 178., 218.,
        66.,  76., 345., 450., 313., 146., 444., 366., 421., 368., 405.,
       139.,  87.,  27., 328., 143., 312., 198., 409., 428., 162.,  97.,
       433., 196.,  43., 277., 458., 462., 113., 262., 465., 359.,   2.,
       414.,  34.,  68., 319.,  26., 159., 370., 204., 336., 334.,  55.,
       119., 304., 231.,  63., 283., 264., 302., 137., 106.,  60., 268.,
       256., 360., 400.,  99., 447., 348., 170., 25

In [43]:
rankdata(sub2['question_asker_intent_understanding'])

array([165., 108., 167., 115., 190., 106., 470., 281., 389., 352., 348.,
        37., 417., 154.,  99., 413., 239.,  38., 232., 160.,  26., 404.,
       120.,  86.,  40., 350., 198., 329., 155., 321., 409., 463.,  77.,
        18.,  84., 228.,  62., 365., 168., 215., 127., 456., 262., 375.,
       335., 199., 101., 355., 390., 346., 377., 364., 130., 366., 183.,
        60.,  68., 444., 261.,  75., 338.,  42., 100., 171., 218., 343.,
       116., 203., 197.,  46., 207., 161., 438., 247., 125., 121., 180.,
       137., 179., 405., 387., 369., 138., 372.,  10., 114., 406.,  61.,
       142.,  96., 169.,  91.,  12., 450.,  14., 284.,  95., 282., 102.,
       445., 399., 468., 437.,  79., 105.,  44., 200., 159., 342., 315.,
       423.,  76., 173.,  83., 206., 257.,  69., 294., 164., 109., 269.,
       151., 347., 465.,  28., 297.,   1., 237.,  33., 107.,  32., 440.,
       475., 251., 314., 368., 371., 174., 234., 184., 286.,  93., 383.,
       318.,   2., 298., 397., 424.,  53., 378., 20